name: Build Engine Wheels

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # We will spin up all three operating systems!
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          submodules: recursive # Ensures pybind11 and glfw are pulled

      - name: Build Wheels (cibuildwheel)
        uses: pypa/cibuildwheel@v2.16.5
        env:
          # Skip PyPy and severely outdated Python versions to save build time
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux_2_28
          CIBW_BEFORE_ALL_LINUX: "dnf install -y libXrandr-devel libXinerama-devel libXcursor-devel libXi-devel"
          CIBW_SKIP: "pp* cp36-* cp37-* *-musllinux*"
          # Force the builder to only compile modern 64-bit architectures
          CIBW_ARCHS: "auto64"
          
          # Force cibuildwheel to use modern C++ standards
          CIBW_ENVIRONMENT: CXXFLAGS="-std=c++17"

      - name: Upload Compiled Wheels
        uses: actions/upload-artifact@v4
        with:
          name: radiance3d-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl