name: Build Engine Wheels

on:
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # We will spin up all three operating systems!
        os: [ windows-latest ]

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          submodules: recursive # Ensures pybind11 and glfw are pulled

      - name: Build Wheels (cibuildwheel)
        uses: pypa/cibuildwheel@v3.4.1
        env:
          CIBW_BUILD: "cp314-win_amd64"
          CIBW_SKIP: "pp* cp36-* cp37-*"
          # Force the builder to only compile modern 64-bit architectures
          CIBW_ARCHS: "auto64"
          
          CIBW_BEFORE_BUILD_WINDOWS: "pip install delvewheel"
          CIBW_REPAIR_WHEEL_COMMAND_WINDOWS: "delvewheel repair -w {dest_dir} {wheel}"
          # Force cibuildwheel to use modern C++ standards
          
          CIBW_ENVIRONMENT: CXXFLAGS="-std=c++17"

      - name: Upload Compiled Wheels
        uses: actions/upload-artifact@v4
        with:
          name: radiance3d-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl